"""Type stubs for `embedcache._native`. Hand-written; keep in sync with
`crates/embedcache-py/src/lib.rs`."""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

__version__: str

class EmbedCacheError(Exception):
    """Raised on redb / IO / malformed-entry errors."""

class EmbedCache:
    def __init__(self, path: str, *, ttl_seconds: int | None = None) -> None: ...
    def get(self, text: str, model: str) -> NDArray[np.float32] | None: ...
    def put(self, text: str, model: str, vector: NDArray[np.float32]) -> None: ...
    def remove(self, text: str, model: str) -> bool: ...
    def clear(self) -> int: ...
    def purge_expired(self) -> int: ...
    def purge_to_size(self, max_bytes: int) -> int: ...
    def stats(self) -> dict[str, int]: ...
    def contains(self, text: str, model: str) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

def key_for(model: str, text: str) -> bytes:
    """Return the 32-byte content-addressed cache key."""
